const PERFORMANCE_DEBUG = false;

const SPREADSHEET_ID = '1TzwkoJ5uYCmniscZ8ATRvWEZgybXtWtlOUZNNwrtKEo';

const SHEETS = {
  PESSOAS: 'DadosPessoais',
  DESAFIO: 'dgmbDesafios',
  REGISTRO_KM: 'REGISTRO_KM',
  MEU_GIRO_RESUMO: 'MEU_GIRO_RESUMO',
  FRASES: 'FRASES',
  LISTA_DESAFIOS: 'ListaDesafios',
  CONFIG_CERTIFICADO_TEMPLATE: 'CONFIG_CERTIFICADO_TEMPLATE'
};
