const SPREADSHEET_ID = '1vC4ivc3DMevxtedDXAVAIsjZxzZbtbP794n63tky0Vw';

const SHEETS = {
  PESSOAS: 'DadosPessoais',
  DESAFIO: 'dgmbDesafios',
  REGISTRO_KM: 'REGISTRO_KM',
  MEU_GIRO_RESUMO: 'MEU_GIRO_RESUMO',
  FRASES: 'FRASES',
  LISTA_DESAFIOS: 'ListaDesafios',
  CONFIG_CERTIFICADO_TEMPLATE: 'CONFIG_CERTIFICADO_TEMPLATE'
};
